name: Test

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    strategy:
      matrix:
        go: [1.16, 1.17, 1.18, 1.19]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    name: Go ${{ matrix.go }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
    
      - name: Test
        run: go test -v ./...
